-- ============================================================================
-- DATABASE UPDATE MIGRATION
-- Adds new tables: Photo Booth, Collection Features, Job Posts
-- Version: 2.0.0
-- Date: 2025-01-XX
-- Description: Adds 8 new tables and 1 column to existing collections table
-- ============================================================================

-- Step 1: Create new enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gallery_privacy_enum') THEN
        CREATE TYPE gallery_privacy_enum AS ENUM ('public', 'password', 'private');
        RAISE NOTICE '✅ Created enum type: gallery_privacy_enum';
    ELSE
        RAISE NOTICE '⚠️  Enum type gallery_privacy_enum already exists';
    END IF;
END
$$;

-- Step 2: Add comments_count to collections table
ALTER TABLE collections 
ADD COLUMN IF NOT EXISTS comments_count INT DEFAULT 0;

COMMENT ON COLUMN collections.comments_count IS 'Count of comments on this collection';

-- Step 3: Create photo_booth_galleries table
CREATE TABLE IF NOT EXISTS photo_booth_galleries (
    gallery_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photographer_id INT NOT NULL,
    booking_id INT,
    event_name VARCHAR(255) NOT NULL,
    qr_code VARCHAR(100) NOT NULL UNIQUE,
    qr_code_url TEXT,
    gallery_url VARCHAR(500) NOT NULL,
    privacy gallery_privacy_enum DEFAULT 'public',
    password_hash VARCHAR(255),
    expiry_date DATE,
    download_enabled BOOLEAN DEFAULT TRUE,
    watermark_enabled BOOLEAN DEFAULT FALSE,
    cover_photo_url VARCHAR(500),
    description TEXT,
    photo_count INT DEFAULT 0,
    access_count INT DEFAULT 0,
    download_count INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photo_booth_galleries_photographer 
        FOREIGN KEY (photographer_id) 
        REFERENCES photographers(photographer_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_photo_booth_galleries_booking 
        FOREIGN KEY (booking_id) 
        REFERENCES bookings(booking_id) 
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_photo_booth_galleries_photographer_id ON photo_booth_galleries(photographer_id);
CREATE INDEX IF NOT EXISTS idx_photo_booth_galleries_booking_id ON photo_booth_galleries(booking_id);
CREATE INDEX IF NOT EXISTS idx_photo_booth_galleries_qr_code ON photo_booth_galleries(qr_code);
CREATE INDEX IF NOT EXISTS idx_photo_booth_galleries_is_active ON photo_booth_galleries(is_active);

COMMENT ON TABLE photo_booth_galleries IS 'Photo booth galleries with QR codes for event photos';

-- Step 4: Create photo_booth_gallery_photos table
CREATE TABLE IF NOT EXISTS photo_booth_gallery_photos (
    photo_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id INT NOT NULL,
    photo_url VARCHAR(500) NOT NULL,
    thumbnail_url VARCHAR(500),
    display_order INT DEFAULT 0,
    download_count INT DEFAULT 0,
    views_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photo_booth_gallery_photos_gallery 
        FOREIGN KEY (gallery_id) 
        REFERENCES photo_booth_galleries(gallery_id) 
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_photo_booth_gallery_photos_gallery_id ON photo_booth_gallery_photos(gallery_id);
CREATE INDEX IF NOT EXISTS idx_photo_booth_gallery_photos_display_order ON photo_booth_gallery_photos(display_order);

COMMENT ON TABLE photo_booth_gallery_photos IS 'Individual photos in photo booth galleries';

-- Step 5: Create photo_booth_access_logs table
CREATE TABLE IF NOT EXISTS photo_booth_access_logs (
    log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id INT NOT NULL,
    ip_address VARCHAR(45),
    user_agent TEXT,
    accessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photo_booth_access_logs_gallery 
        FOREIGN KEY (gallery_id) 
        REFERENCES photo_booth_galleries(gallery_id) 
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_photo_booth_access_logs_gallery_id ON photo_booth_access_logs(gallery_id);
CREATE INDEX IF NOT EXISTS idx_photo_booth_access_logs_accessed_at ON photo_booth_access_logs(accessed_at);

COMMENT ON TABLE photo_booth_access_logs IS 'Access tracking for photo booth galleries (analytics)';

-- Step 6: Create collection_likes table
CREATE TABLE IF NOT EXISTS collection_likes (
    like_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id INT NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_collection_likes_collection 
        FOREIGN KEY (collection_id) 
        REFERENCES collections(collection_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_collection_likes_user 
        FOREIGN KEY (user_id) 
        REFERENCES users(user_id) 
        ON DELETE CASCADE,
    CONSTRAINT uq_collection_like UNIQUE (collection_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_collection_likes_collection_id ON collection_likes(collection_id);
CREATE INDEX IF NOT EXISTS idx_collection_likes_user_id ON collection_likes(user_id);

COMMENT ON TABLE collection_likes IS 'Track likes on collections/moodboards';

-- Step 7: Create collection_comments table
CREATE TABLE IF NOT EXISTS collection_comments (
    comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id INT NOT NULL,
    user_id INT NOT NULL,
    parent_comment_id INT,
    comment_text TEXT NOT NULL,
    likes_count INT DEFAULT 0,
    is_edited BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_collection_comments_collection 
        FOREIGN KEY (collection_id) 
        REFERENCES collections(collection_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_collection_comments_user 
        FOREIGN KEY (user_id) 
        REFERENCES users(user_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_collection_comments_parent 
        FOREIGN KEY (parent_comment_id) 
        REFERENCES collection_comments(comment_id) 
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_collection_comments_collection_id ON collection_comments(collection_id);
CREATE INDEX IF NOT EXISTS idx_collection_comments_user_id ON collection_comments(user_id);
CREATE INDEX IF NOT EXISTS idx_collection_comments_parent_comment_id ON collection_comments(parent_comment_id);

COMMENT ON TABLE collection_comments IS 'Comments on collections/moodboards';

-- Step 8: Create board_collaborators table
CREATE TABLE IF NOT EXISTS board_collaborators (
    collaborator_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id INT NOT NULL,
    user_id INT NOT NULL,
    permission_level VARCHAR(20) NOT NULL DEFAULT 'view',
    status VARCHAR(20) DEFAULT 'active',
    invited_by INT,
    invited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_board_collaborators_collection 
        FOREIGN KEY (collection_id) 
        REFERENCES collections(collection_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_board_collaborators_user 
        FOREIGN KEY (user_id) 
        REFERENCES users(user_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_board_collaborators_invited_by 
        FOREIGN KEY (invited_by) 
        REFERENCES users(user_id) 
        ON DELETE SET NULL,
    CONSTRAINT uq_board_collaborator UNIQUE (collection_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_board_collaborators_collection_id ON board_collaborators(collection_id);
CREATE INDEX IF NOT EXISTS idx_board_collaborators_user_id ON board_collaborators(user_id);
CREATE INDEX IF NOT EXISTS idx_board_collaborators_status ON board_collaborators(status);

COMMENT ON TABLE board_collaborators IS 'Collaborative moodboards - users who can edit/view collections';

-- Step 9: Create job_posts table
CREATE TABLE IF NOT EXISTS job_posts (
    job_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photographer_id INT NOT NULL,
    posted_by_user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    job_title VARCHAR(255) NOT NULL,
    job_description TEXT,
    category VARCHAR(100),
    budget_min DECIMAL(10, 2),
    budget_max DECIMAL(10, 2),
    duration VARCHAR(50),
    urgency VARCHAR(20) DEFAULT 'normal',
    location VARCHAR(255),
    required_skills JSONB,
    application_deadline DATE,
    max_collaborators INT,
    is_remote BOOLEAN DEFAULT FALSE,
    status VARCHAR(20) DEFAULT 'open',
    view_count INT DEFAULT 0,
    applications_count INT DEFAULT 0,
    archived_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_job_posts_photographer 
        FOREIGN KEY (photographer_id) 
        REFERENCES photographers(photographer_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_job_posts_user 
        FOREIGN KEY (posted_by_user_id) 
        REFERENCES users(user_id) 
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_job_posts_photographer_id ON job_posts(photographer_id);
CREATE INDEX IF NOT EXISTS idx_job_posts_posted_by_user_id ON job_posts(posted_by_user_id);
CREATE INDEX IF NOT EXISTS idx_job_posts_status ON job_posts(status);
CREATE INDEX IF NOT EXISTS idx_job_posts_category ON job_posts(category);
CREATE INDEX IF NOT EXISTS idx_job_posts_location ON job_posts(location);

COMMENT ON TABLE job_posts IS 'Job postings by photographers looking for collaborators/assistants';

-- Step 10: Create job_applications table
CREATE TABLE IF NOT EXISTS job_applications (
    application_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INT NOT NULL,
    applicant_id INT NOT NULL,
    applicant_name VARCHAR(255) NOT NULL,
    applicant_email VARCHAR(255) NOT NULL,
    applicant_phone VARCHAR(20),
    cover_letter TEXT,
    portfolio_url VARCHAR(500),
    experience_years INT,
    expected_rate DECIMAL(10, 2),
    availability_start DATE,
    availability_end DATE,
    additional_info TEXT,
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_job_applications_job 
        FOREIGN KEY (job_id) 
        REFERENCES job_posts(job_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_job_applications_applicant 
        FOREIGN KEY (applicant_id) 
        REFERENCES users(user_id) 
        ON DELETE CASCADE,
    CONSTRAINT uq_job_application UNIQUE (job_id, applicant_id)
);

CREATE INDEX IF NOT EXISTS idx_job_applications_job_id ON job_applications(job_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_applicant_id ON job_applications(applicant_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_status ON job_applications(status);

COMMENT ON TABLE job_applications IS 'Applications submitted for job posts';

-- Add triggers for updated_at columns
DROP TRIGGER IF EXISTS photo_booth_galleries_set_timestamp ON photo_booth_galleries;
CREATE TRIGGER photo_booth_galleries_set_timestamp
BEFORE UPDATE ON photo_booth_galleries
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS collection_comments_set_timestamp ON collection_comments;
CREATE TRIGGER collection_comments_set_timestamp
BEFORE UPDATE ON collection_comments
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS board_collaborators_set_timestamp ON board_collaborators;
CREATE TRIGGER board_collaborators_set_timestamp
BEFORE UPDATE ON board_collaborators
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS job_posts_set_timestamp ON job_posts;
CREATE TRIGGER job_posts_set_timestamp
BEFORE UPDATE ON job_posts
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS job_applications_set_timestamp ON job_applications;
CREATE TRIGGER job_applications_set_timestamp
BEFORE UPDATE ON job_applications
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Verification
DO $$
BEGIN
    RAISE NOTICE '============================================================================';
    RAISE NOTICE '✅ DATABASE UPDATE MIGRATION COMPLETED SUCCESSFULLY!';
    RAISE NOTICE '============================================================================';
    RAISE NOTICE '✅ Added 1 new enum type: gallery_privacy_enum';
    RAISE NOTICE '✅ Added 8 new tables:';
    RAISE NOTICE '   1. photo_booth_galleries';
    RAISE NOTICE '   2. photo_booth_gallery_photos';
    RAISE NOTICE '   3. photo_booth_access_logs';
    RAISE NOTICE '   4. collection_likes';
    RAISE NOTICE '   5. collection_comments';
    RAISE NOTICE '   6. board_collaborators';
    RAISE NOTICE '   7. job_posts';
    RAISE NOTICE '   8. job_applications';
    RAISE NOTICE '✅ Updated collections table: added comments_count column';
    RAISE NOTICE '✅ All indexes and triggers created';
    RAISE NOTICE '============================================================================';
END
$$;












