-- ============================================================================
-- PHOTO BOOTH TABLES MIGRATION
-- Description: Creates tables for Photo Booth QR code gallery feature
-- Date: 2025-12-28
-- ============================================================================

-- ============================================================================
-- ENUM TYPE FOR GALLERY PRIVACY
-- ============================================================================

-- Create ENUM type for gallery privacy (single-line for pgAdmin compatibility)
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gallery_privacy_enum') THEN CREATE TYPE gallery_privacy_enum AS ENUM ('public', 'password', 'private'); END IF; END $$;

-- ============================================================================
-- TABLE: photo_booth_galleries
-- Purpose: Stores Photo Booth gallery information and settings
-- ============================================================================

CREATE TABLE IF NOT EXISTS photo_booth_galleries (
    gallery_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photographer_id INT NOT NULL,
    booking_id INT,
    event_name VARCHAR(255) NOT NULL,
    qr_code VARCHAR(100) NOT NULL UNIQUE,
    qr_code_url VARCHAR(500),
    gallery_url VARCHAR(500) NOT NULL,
    privacy gallery_privacy_enum DEFAULT 'public',
    password_hash VARCHAR(255),
    expiry_date DATE,
    download_enabled BOOLEAN DEFAULT TRUE,
    watermark_enabled BOOLEAN DEFAULT FALSE,
    cover_photo_url VARCHAR(500),
    description TEXT,
    photo_count INT DEFAULT 0,
    access_count INT DEFAULT 0,
    download_count INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photo_booth_galleries_photographer 
        FOREIGN KEY (photographer_id) 
        REFERENCES photographers(photographer_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_photo_booth_galleries_booking 
        FOREIGN KEY (booking_id) 
        REFERENCES bookings(booking_id) 
        ON DELETE SET NULL
);

-- Indexes for photo_booth_galleries
CREATE INDEX IF NOT EXISTS idx_photo_booth_galleries_photographer_id 
    ON photo_booth_galleries(photographer_id);
CREATE INDEX IF NOT EXISTS idx_photo_booth_galleries_qr_code 
    ON photo_booth_galleries(qr_code);
CREATE INDEX IF NOT EXISTS idx_photo_booth_galleries_privacy 
    ON photo_booth_galleries(privacy);
CREATE INDEX IF NOT EXISTS idx_photo_booth_galleries_is_active 
    ON photo_booth_galleries(is_active);
CREATE INDEX IF NOT EXISTS idx_photo_booth_galleries_booking_id 
    ON photo_booth_galleries(booking_id);
CREATE INDEX IF NOT EXISTS idx_photo_booth_galleries_created_at 
    ON photo_booth_galleries(created_at);

-- ============================================================================
-- TABLE: photo_booth_gallery_photos
-- Purpose: Stores photos associated with each Photo Booth gallery
-- ============================================================================

CREATE TABLE IF NOT EXISTS photo_booth_gallery_photos (
    photo_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id INT NOT NULL,
    photo_url VARCHAR(500) NOT NULL,
    thumbnail_url VARCHAR(500),
    display_order INT DEFAULT 0,
    download_count INT DEFAULT 0,
    views_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photo_booth_gallery_photos_gallery 
        FOREIGN KEY (gallery_id) 
        REFERENCES photo_booth_galleries(gallery_id) 
        ON DELETE CASCADE
);

-- Indexes for photo_booth_gallery_photos
CREATE INDEX IF NOT EXISTS idx_photo_booth_gallery_photos_gallery_id 
    ON photo_booth_gallery_photos(gallery_id);
CREATE INDEX IF NOT EXISTS idx_photo_booth_gallery_photos_display_order 
    ON photo_booth_gallery_photos(gallery_id, display_order);

-- ============================================================================
-- TABLE: photo_booth_access_logs
-- Purpose: Tracks access to Photo Booth galleries for analytics
-- ============================================================================

CREATE TABLE IF NOT EXISTS photo_booth_access_logs (
    log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id INT NOT NULL,
    ip_address VARCHAR(45),
    user_agent TEXT,
    accessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photo_booth_access_logs_gallery 
        FOREIGN KEY (gallery_id) 
        REFERENCES photo_booth_galleries(gallery_id) 
        ON DELETE CASCADE
);

-- Indexes for photo_booth_access_logs
CREATE INDEX IF NOT EXISTS idx_photo_booth_access_logs_gallery_id 
    ON photo_booth_access_logs(gallery_id);
CREATE INDEX IF NOT EXISTS idx_photo_booth_access_logs_accessed_at 
    ON photo_booth_access_logs(accessed_at);
CREATE INDEX IF NOT EXISTS idx_photo_booth_access_logs_gallery_accessed 
    ON photo_booth_access_logs(gallery_id, accessed_at);

-- ============================================================================
-- TRIGGER: Update updated_at timestamp for photo_booth_galleries
-- ============================================================================

DROP TRIGGER IF EXISTS update_photo_booth_galleries_updated_at ON photo_booth_galleries;

CREATE TRIGGER update_photo_booth_galleries_updated_at
    BEFORE UPDATE ON photo_booth_galleries
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================

