-- ============================================================================
-- SIMPLE VERSION - Create job_applications table without foreign keys first
-- ============================================================================
-- Run this version if you're getting foreign key errors
-- You can add foreign keys later once you verify the referenced tables exist

-- Drop table if exists (use with caution - this will delete all data!)
-- DROP TABLE IF EXISTS job_applications CASCADE;

-- Create the table
CREATE TABLE IF NOT EXISTS job_applications (
    application_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INT NOT NULL,
    applicant_id INT NOT NULL,
    applicant_name VARCHAR(255) NOT NULL,
    applicant_email VARCHAR(255) NOT NULL,
    applicant_phone VARCHAR(20),
    cover_letter TEXT,
    portfolio_url VARCHAR(500),
    experience_years INT,
    expected_rate DECIMAL(10, 2),
    availability_start DATE,
    availability_end DATE,
    additional_info TEXT,
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_job_applications_job_id ON job_applications(job_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_applicant_id ON job_applications(applicant_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_status ON job_applications(status);
CREATE INDEX IF NOT EXISTS idx_job_applications_created_at ON job_applications(created_at);

-- Add trigger function
CREATE OR REPLACE FUNCTION update_job_applications_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger
DROP TRIGGER IF EXISTS job_applications_update_timestamp ON job_applications;
CREATE TRIGGER job_applications_update_timestamp
    BEFORE UPDATE ON job_applications
    FOR EACH ROW
    EXECUTE FUNCTION update_job_applications_updated_at();

-- ============================================================================
-- ADD FOREIGN KEYS LATER (run these separately after verifying tables exist)
-- ============================================================================
-- First verify the tables exist:
-- SELECT table_name FROM information_schema.tables 
-- WHERE table_schema = 'public' AND table_name IN ('job_posts', 'users');

-- Then add foreign keys:
/*
ALTER TABLE job_applications 
ADD CONSTRAINT fk_job_applications_job 
FOREIGN KEY (job_id) REFERENCES job_posts(job_id) ON DELETE CASCADE;

ALTER TABLE job_applications 
ADD CONSTRAINT fk_job_applications_applicant 
FOREIGN KEY (applicant_id) REFERENCES users(user_id) ON DELETE CASCADE;
*/
