-- Create job_applications table
CREATE TABLE IF NOT EXISTS job_applications (
    application_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INT NOT NULL,
    applicant_id INT NOT NULL,
    applicant_name VARCHAR(255) NOT NULL,
    applicant_email VARCHAR(255) NOT NULL,
    applicant_phone VARCHAR(20),
    cover_letter TEXT,
    portfolio_url VARCHAR(500),
    experience_years INT,
    expected_rate DECIMAL(10, 2),
    availability_start DATE,
    availability_end DATE,
    additional_info TEXT,
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_job_applications_job FOREIGN KEY (job_id) REFERENCES job_posts(job_id) ON DELETE CASCADE,
    CONSTRAINT fk_job_applications_applicant FOREIGN KEY (applicant_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_job_applications_job_id ON job_applications(job_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_applicant_id ON job_applications(applicant_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_status ON job_applications(status);
