-- ============================================================================
-- CHITRASETHU POSTGRESQL - INDIVIDUAL TABLE CREATE QUERIES
-- Complete collection of CREATE TABLE statements for all database tables
-- Version: 1.0.0
-- ============================================================================

-- ============================================================================
-- ENUM TYPES (Required before creating tables)
-- ============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_type_enum') THEN
        CREATE TYPE user_type_enum AS ENUM ('customer', 'photographer', 'admin');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gender_enum') THEN
        CREATE TYPE gender_enum AS ENUM ('male', 'female', 'other', 'prefer_not_to_say');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_status_enum') THEN
        CREATE TYPE event_status_enum AS ENUM ('open', 'in_progress', 'completed', 'cancelled');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_visibility_enum') THEN
        CREATE TYPE event_visibility_enum AS ENUM ('public', 'private');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'booking_status_enum') THEN
        CREATE TYPE booking_status_enum AS ENUM ('pending', 'confirmed', 'in_progress', 'completed', 'cancelled', 'refunded');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'booking_payment_status_enum') THEN
        CREATE TYPE booking_payment_status_enum AS ENUM ('unpaid', 'partial', 'paid', 'refunded');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_type_enum') THEN
        CREATE TYPE payment_type_enum AS ENUM ('advance', 'partial', 'full', 'refund');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status_enum') THEN
        CREATE TYPE payment_status_enum AS ENUM ('pending', 'processing', 'completed', 'failed', 'refunded');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'post_content_type_enum') THEN
        CREATE TYPE post_content_type_enum AS ENUM ('image', 'video', 'text', 'gallery');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'post_visibility_enum') THEN
        CREATE TYPE post_visibility_enum AS ENUM ('public', 'followers', 'private');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'message_type_enum') THEN
        CREATE TYPE message_type_enum AS ENUM ('text', 'image', 'file');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_type_enum') THEN
        CREATE TYPE notification_type_enum AS ENUM ('booking', 'message', 'like', 'comment', 'review', 'payment', 'system');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_priority_enum') THEN
        CREATE TYPE notification_priority_enum AS ENUM ('low', 'medium', 'high');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gallery_privacy_enum') THEN
        CREATE TYPE gallery_privacy_enum AS ENUM ('public', 'password', 'private');
    END IF;
END
$$;

-- ============================================================================
-- 1. USERS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    user_type user_type_enum NOT NULL DEFAULT 'customer',
    is_verified BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    verification_token VARCHAR(255),
    reset_password_token VARCHAR(255),
    reset_password_expires TIMESTAMP,
    last_login TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 2. USER_PROFILES TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS user_profiles (
    profile_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(500),
    avatar_public_id VARCHAR(255),
    bio TEXT,
    phone VARCHAR(20),
    location VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100) DEFAULT 'India',
    pincode VARCHAR(10),
    date_of_birth DATE,
    gender gender_enum,
    social_links JSONB,
    preferences JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- ============================================================================
-- 3. USER_ROLES TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS user_roles (
    role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    description TEXT,
    permissions JSONB,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 4. USER_SESSIONS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS user_sessions (
    session_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    token VARCHAR(500) NOT NULL UNIQUE,
    device_info VARCHAR(255),
    ip_address VARCHAR(45),
    user_agent TEXT,
    expires_at TIMESTAMP NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- ============================================================================
-- 5. PHOTOGRAPHERS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS photographers (
    photographer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    business_name VARCHAR(255),
    specialties JSONB NOT NULL,
    experience_years INT DEFAULT 0,
    base_price DECIMAL(10, 2),
    currency VARCHAR(10) DEFAULT 'INR',
    rating DECIMAL(3, 2) DEFAULT 0.00,
    total_reviews INT DEFAULT 0,
    total_bookings INT DEFAULT 0,
    equipment JSONB,
    languages JSONB,
    services_offered JSONB,
    certifications TEXT,
    awards TEXT,
    work_radius INT DEFAULT 50,
    is_verified BOOLEAN DEFAULT FALSE,
    is_premium BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    verification_date TIMESTAMP,
    premium_until TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photographers_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- ============================================================================
-- 6. PHOTOGRAPHER_PORTFOLIOS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS photographer_portfolios (
    portfolio_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photographer_id INT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    thumbnail_url VARCHAR(500),
    public_id VARCHAR(255),
    width INT,
    height INT,
    format VARCHAR(10),
    bytes BIGINT,
    cloudinary_folder VARCHAR(255),
    title VARCHAR(255),
    description TEXT,
    category VARCHAR(100),
    tags JSONB,
    display_order INT DEFAULT 0,
    likes_count INT DEFAULT 0,
    views_count INT DEFAULT 0,
    is_featured BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    post_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_portfolios_photographer FOREIGN KEY (photographer_id) REFERENCES photographers(photographer_id) ON DELETE CASCADE
);

-- ============================================================================
-- 7. PHOTOGRAPHER_AVAILABILITY TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS photographer_availability (
    availability_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photographer_id INT NOT NULL,
    date DATE NOT NULL,
    time_slot VARCHAR(50) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_available BOOLEAN DEFAULT TRUE,
    booking_id INT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_availability_photographer FOREIGN KEY (photographer_id) REFERENCES photographers(photographer_id) ON DELETE CASCADE,
    CONSTRAINT uq_photographer_availability UNIQUE (photographer_id, date, time_slot)
);

-- ============================================================================
-- 8. EVENT_CATEGORIES TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS event_categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    icon VARCHAR(100),
    color_code VARCHAR(20),
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 9. EVENTS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS events (
    event_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id INT NOT NULL,
    category_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    event_date DATE NOT NULL,
    event_time TIME,
    end_date DATE,
    location VARCHAR(255),
    venue_name VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    expected_attendees INT,
    budget_range VARCHAR(100),
    min_budget DECIMAL(10, 2),
    max_budget DECIMAL(10, 2),
    requirements TEXT,
    status event_status_enum DEFAULT 'open',
    visibility event_visibility_enum DEFAULT 'public',
    images JSONB,
    tags JSONB,
    views_count INT DEFAULT 0,
    interested_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_events_creator FOREIGN KEY (creator_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES event_categories(category_id)
);

-- ============================================================================
-- 10. BOOKINGS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS bookings (
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    photographer_id INT NOT NULL,
    event_id INT,
    booking_date DATE NOT NULL,
    booking_time TIME,
    end_date DATE,
    duration_hours DECIMAL(5, 2),
    location VARCHAR(255),
    venue_name VARCHAR(255),
    event_type VARCHAR(100),
    total_amount DECIMAL(10, 2) NOT NULL,
    advance_amount DECIMAL(10, 2),
    pending_amount DECIMAL(10, 2),
    currency VARCHAR(10) DEFAULT 'INR',
    status booking_status_enum DEFAULT 'pending',
    payment_status booking_payment_status_enum DEFAULT 'unpaid',
    special_requirements TEXT,
    cancellation_reason TEXT,
    cancelled_by INT,
    cancelled_at TIMESTAMP,
    confirmed_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookings_customer FOREIGN KEY (customer_id) REFERENCES users(user_id),
    CONSTRAINT fk_bookings_photographer FOREIGN KEY (photographer_id) REFERENCES photographers(photographer_id),
    CONSTRAINT fk_bookings_event FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE SET NULL
);

-- ============================================================================
-- 11. BOOKING_PAYMENTS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS booking_payments (
    payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'INR',
    payment_type payment_type_enum NOT NULL,
    payment_method VARCHAR(50),
    payment_status payment_status_enum DEFAULT 'pending',
    transaction_id VARCHAR(255) UNIQUE,
    payment_gateway VARCHAR(50),
    gateway_response JSONB,
    payment_date TIMESTAMP,
    refund_amount DECIMAL(10, 2),
    refund_date TIMESTAMP,
    refund_reason TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE
);

-- ============================================================================
-- 12. BOOKING_REVIEWS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS booking_reviews (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT NOT NULL UNIQUE,
    photographer_id INT NOT NULL,
    customer_id INT NOT NULL,
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_text TEXT,
    review_images JSONB,
    response_text TEXT,
    response_date TIMESTAMP,
    is_verified BOOLEAN DEFAULT FALSE,
    is_featured BOOLEAN DEFAULT FALSE,
    helpful_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_photographer FOREIGN KEY (photographer_id) REFERENCES photographers(photographer_id),
    CONSTRAINT fk_reviews_customer FOREIGN KEY (customer_id) REFERENCES users(user_id)
);

-- ============================================================================
-- 13. POSTS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS posts (
    post_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    content_type post_content_type_enum NOT NULL DEFAULT 'image',
    caption TEXT,
    media_urls JSONB,
    thumbnail_url VARCHAR(500),
    location VARCHAR(255),
    tags JSONB,
    mentions JSONB,
    likes_count INT DEFAULT 0,
    comments_count INT DEFAULT 0,
    shares_count INT DEFAULT 0,
    views_count INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    is_featured BOOLEAN DEFAULT FALSE,
    visibility post_visibility_enum DEFAULT 'public',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- ============================================================================
-- 14. POST_LIKES TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS post_likes (
    like_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INT NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
    CONSTRAINT fk_post_likes_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_post_like UNIQUE (post_id, user_id)
);

-- ============================================================================
-- 15. POST_COMMENTS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS post_comments (
    comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INT NOT NULL,
    user_id INT NOT NULL,
    parent_comment_id INT,
    comment_text TEXT NOT NULL,
    likes_count INT DEFAULT 0,
    is_edited BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_post_comments_post FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
    CONSTRAINT fk_post_comments_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_post_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES post_comments(comment_id) ON DELETE CASCADE
);

-- ============================================================================
-- 16. COLLECTIONS TABLE (Moodboards)
-- ============================================================================

CREATE TABLE IF NOT EXISTS collections (
    collection_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    thumbnail_url VARCHAR(500),
    images JSONB,
    category VARCHAR(100),
    tags JSONB,
    is_public BOOLEAN DEFAULT TRUE,
    likes_count INT DEFAULT 0,
    saves_count INT DEFAULT 0,
    views_count INT DEFAULT 0,
    comments_count INT DEFAULT 0,
    is_featured BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_collections_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- ============================================================================
-- 17. MESSAGES TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS messages (
    message_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INT NOT NULL,
    receiver_id INT NOT NULL,
    message_text TEXT NOT NULL,
    message_type message_type_enum DEFAULT 'text',
    attachment_url VARCHAR(500),
    attachment_public_id VARCHAR(255),
    is_read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMP,
    is_deleted_by_sender BOOLEAN DEFAULT FALSE,
    is_deleted_by_receiver BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_receiver FOREIGN KEY (receiver_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- ============================================================================
-- 18. NOTIFICATIONS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS notifications (
    notification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    type notification_type_enum NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    link VARCHAR(500),
    data JSONB,
    is_read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMP,
    priority notification_priority_enum DEFAULT 'medium',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- ============================================================================
-- 19. PHOTO_BOOTH_GALLERIES TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS photo_booth_galleries (
    gallery_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photographer_id INT NOT NULL,
    booking_id INT,
    event_name VARCHAR(255) NOT NULL,
    qr_code VARCHAR(100) NOT NULL UNIQUE,
    qr_code_url TEXT,
    gallery_url VARCHAR(500) NOT NULL,
    privacy gallery_privacy_enum DEFAULT 'public',
    password_hash VARCHAR(255),
    expiry_date DATE,
    download_enabled BOOLEAN DEFAULT TRUE,
    watermark_enabled BOOLEAN DEFAULT FALSE,
    cover_photo_url VARCHAR(500),
    description TEXT,
    photo_count INT DEFAULT 0,
    access_count INT DEFAULT 0,
    download_count INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photo_booth_galleries_photographer 
        FOREIGN KEY (photographer_id) 
        REFERENCES photographers(photographer_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_photo_booth_galleries_booking 
        FOREIGN KEY (booking_id) 
        REFERENCES bookings(booking_id) 
        ON DELETE SET NULL
);

-- ============================================================================
-- 20. PHOTO_BOOTH_GALLERY_PHOTOS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS photo_booth_gallery_photos (
    photo_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id INT NOT NULL,
    photo_url VARCHAR(500) NOT NULL,
    thumbnail_url VARCHAR(500),
    display_order INT DEFAULT 0,
    download_count INT DEFAULT 0,
    views_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photo_booth_gallery_photos_gallery 
        FOREIGN KEY (gallery_id) 
        REFERENCES photo_booth_galleries(gallery_id) 
        ON DELETE CASCADE
);

-- ============================================================================
-- 21. PHOTO_BOOTH_ACCESS_LOGS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS photo_booth_access_logs (
    log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gallery_id INT NOT NULL,
    ip_address VARCHAR(45),
    user_agent TEXT,
    accessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photo_booth_access_logs_gallery 
        FOREIGN KEY (gallery_id) 
        REFERENCES photo_booth_galleries(gallery_id) 
        ON DELETE CASCADE
);

-- ============================================================================
-- 22. COLLECTION_LIKES TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS collection_likes (
    like_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id INT NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_collection_likes_collection FOREIGN KEY (collection_id) REFERENCES collections(collection_id) ON DELETE CASCADE,
    CONSTRAINT fk_collection_likes_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_collection_like UNIQUE (collection_id, user_id)
);

-- ============================================================================
-- 23. COLLECTION_COMMENTS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS collection_comments (
    comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id INT NOT NULL,
    user_id INT NOT NULL,
    parent_comment_id INT,
    comment_text TEXT NOT NULL,
    likes_count INT DEFAULT 0,
    is_edited BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_collection_comments_collection FOREIGN KEY (collection_id) REFERENCES collections(collection_id) ON DELETE CASCADE,
    CONSTRAINT fk_collection_comments_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_collection_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES collection_comments(comment_id) ON DELETE CASCADE
);

-- ============================================================================
-- 24. BOARD_COLLABORATORS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS board_collaborators (
    collaborator_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id INT NOT NULL,
    user_id INT NOT NULL,
    permission_level VARCHAR(20) NOT NULL DEFAULT 'view',
    status VARCHAR(20) DEFAULT 'active',
    invited_by INT,
    invited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_board_collaborators_collection FOREIGN KEY (collection_id) REFERENCES collections(collection_id) ON DELETE CASCADE,
    CONSTRAINT fk_board_collaborators_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_board_collaborators_invited_by FOREIGN KEY (invited_by) REFERENCES users(user_id) ON DELETE SET NULL,
    CONSTRAINT uq_board_collaborator UNIQUE (collection_id, user_id)
);

-- ============================================================================
-- 25. JOB_POSTS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS job_posts (
    job_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photographer_id INT NOT NULL,
    posted_by_user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    job_title VARCHAR(255) NOT NULL,
    job_description TEXT,
    category VARCHAR(100),
    budget_min DECIMAL(10, 2),
    budget_max DECIMAL(10, 2),
    duration VARCHAR(50),
    urgency VARCHAR(20) DEFAULT 'normal',
    location VARCHAR(255),
    required_skills JSONB,
    application_deadline DATE,
    max_collaborators INT,
    is_remote BOOLEAN DEFAULT FALSE,
    status VARCHAR(20) DEFAULT 'open',
    view_count INT DEFAULT 0,
    applications_count INT DEFAULT 0,
    archived_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_job_posts_photographer FOREIGN KEY (photographer_id) REFERENCES photographers(photographer_id) ON DELETE CASCADE,
    CONSTRAINT fk_job_posts_user FOREIGN KEY (posted_by_user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- ============================================================================
-- 26. JOB_APPLICATIONS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS job_applications (
    application_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INT NOT NULL,
    applicant_id INT NOT NULL,
    applicant_name VARCHAR(255) NOT NULL,
    applicant_email VARCHAR(255) NOT NULL,
    applicant_phone VARCHAR(20),
    cover_letter TEXT,
    portfolio_url VARCHAR(500),
    experience_years INT,
    expected_rate DECIMAL(10, 2),
    availability_start DATE,
    availability_end DATE,
    additional_info TEXT,
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_job_applications_job FOREIGN KEY (job_id) REFERENCES job_posts(job_id) ON DELETE CASCADE,
    CONSTRAINT fk_job_applications_applicant FOREIGN KEY (applicant_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_job_application UNIQUE (job_id, applicant_id)
);

-- ============================================================================
-- END OF ALL TABLE QUERIES
-- ============================================================================
