-- ============================================================================
-- CHITRASETHU POSTGRESQL DATABASE SCHEMA
-- Version: 1.0.0
-- Date: 2025-11-12
-- Description: PostgreSQL-compatible schema for Chitrasethu Photography Platform
-- ============================================================================

-- Drop and recreate database (use with caution in development environments)
-- DROP DATABASE IF EXISTS chitrasethu;
-- CREATE DATABASE chitrasethu;

-- Connect to the database
-- \c chitrasethu

-- ============================================================================
-- EXTENSIONS
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- ENUM TYPES
-- ============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_type_enum') THEN
        CREATE TYPE user_type_enum AS ENUM ('customer', 'photographer', 'admin');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gender_enum') THEN
        CREATE TYPE gender_enum AS ENUM ('male', 'female', 'other', 'prefer_not_to_say');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_status_enum') THEN
        CREATE TYPE event_status_enum AS ENUM ('open', 'in_progress', 'completed', 'cancelled');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_visibility_enum') THEN
        CREATE TYPE event_visibility_enum AS ENUM ('public', 'private');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'booking_status_enum') THEN
        CREATE TYPE booking_status_enum AS ENUM ('pending', 'confirmed', 'in_progress', 'completed', 'cancelled', 'refunded');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'booking_payment_status_enum') THEN
        CREATE TYPE booking_payment_status_enum AS ENUM ('unpaid', 'partial', 'paid', 'refunded');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_type_enum') THEN
        CREATE TYPE payment_type_enum AS ENUM ('advance', 'partial', 'full', 'refund');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status_enum') THEN
        CREATE TYPE payment_status_enum AS ENUM ('pending', 'processing', 'completed', 'failed', 'refunded');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'post_content_type_enum') THEN
        CREATE TYPE post_content_type_enum AS ENUM ('image', 'video', 'text', 'gallery');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'post_visibility_enum') THEN
        CREATE TYPE post_visibility_enum AS ENUM ('public', 'followers', 'private');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'message_type_enum') THEN
        CREATE TYPE message_type_enum AS ENUM ('text', 'image', 'file');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_type_enum') THEN
        CREATE TYPE notification_type_enum AS ENUM ('booking', 'message', 'like', 'comment', 'review', 'payment', 'system');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_priority_enum') THEN
        CREATE TYPE notification_priority_enum AS ENUM ('low', 'medium', 'high');
    END IF;
END
$$;

-- ============================================================================
-- UTILITY FUNCTIONS & TRIGGERS
-- ============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 1. USER MANAGEMENT TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    user_type user_type_enum NOT NULL DEFAULT 'customer',
    is_verified BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    verification_token VARCHAR(255),
    reset_password_token VARCHAR(255),
    reset_password_expires TIMESTAMP,
    last_login TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_user_type ON users(user_type);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active);

CREATE TABLE IF NOT EXISTS user_profiles (
    profile_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(500),
    bio TEXT,
    phone VARCHAR(20),
    location VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100) DEFAULT 'India',
    pincode VARCHAR(10),
    date_of_birth DATE,
    gender gender_enum,
    social_links JSONB,
    preferences JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_profiles_location ON user_profiles(city, state);
CREATE INDEX IF NOT EXISTS idx_user_profiles_full_name ON user_profiles(full_name);

CREATE TABLE IF NOT EXISTS user_roles (
    role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    description TEXT,
    permissions JSONB,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_roles_name ON user_roles(role_name);

CREATE TABLE IF NOT EXISTS user_sessions (
    session_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    token VARCHAR(500) NOT NULL UNIQUE,
    device_info VARCHAR(255),
    ip_address VARCHAR(45),
    user_agent TEXT,
    expires_at TIMESTAMP NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_token ON user_sessions(token);
CREATE INDEX IF NOT EXISTS idx_user_sessions_expires_at ON user_sessions(expires_at);

-- ============================================================================
-- 2. PHOTOGRAPHER MANAGEMENT TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS photographers (
    photographer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    business_name VARCHAR(255),
    specialties JSONB NOT NULL,
    experience_years INT DEFAULT 0,
    base_price DECIMAL(10, 2),
    currency VARCHAR(10) DEFAULT 'INR',
    rating DECIMAL(3, 2) DEFAULT 0.00,
    total_reviews INT DEFAULT 0,
    total_bookings INT DEFAULT 0,
    equipment JSONB,
    languages JSONB,
    services_offered JSONB,
    work_radius INT DEFAULT 50,
    is_verified BOOLEAN DEFAULT FALSE,
    is_premium BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    verification_date TIMESTAMP,
    premium_until TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photographers_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_photographers_rating ON photographers(rating);
CREATE INDEX IF NOT EXISTS idx_photographers_is_verified ON photographers(is_verified);
CREATE INDEX IF NOT EXISTS idx_photographers_is_premium ON photographers(is_premium);
CREATE INDEX IF NOT EXISTS idx_photographers_base_price ON photographers(base_price);

CREATE TABLE IF NOT EXISTS photographer_portfolios (
    portfolio_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photographer_id INT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    thumbnail_url VARCHAR(500),
    title VARCHAR(255),
    description TEXT,
    category VARCHAR(100),
    tags JSONB,
    display_order INT DEFAULT 0,
    likes_count INT DEFAULT 0,
    views_count INT DEFAULT 0,
    is_featured BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_portfolios_photographer FOREIGN KEY (photographer_id) REFERENCES photographers(photographer_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_portfolios_photographer_id ON photographer_portfolios(photographer_id);
CREATE INDEX IF NOT EXISTS idx_portfolios_category ON photographer_portfolios(category);
CREATE INDEX IF NOT EXISTS idx_portfolios_display_order ON photographer_portfolios(display_order);
CREATE INDEX IF NOT EXISTS idx_portfolios_is_featured ON photographer_portfolios(is_featured);

CREATE TABLE IF NOT EXISTS photographer_availability (
    availability_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photographer_id INT NOT NULL,
    date DATE NOT NULL,
    time_slot VARCHAR(50) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_available BOOLEAN DEFAULT TRUE,
    booking_id INT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_availability_photographer FOREIGN KEY (photographer_id) REFERENCES photographers(photographer_id) ON DELETE CASCADE,
    CONSTRAINT uq_photographer_availability UNIQUE (photographer_id, date, time_slot)
);

CREATE INDEX IF NOT EXISTS idx_availability_photographer_date ON photographer_availability(photographer_id, date);
CREATE INDEX IF NOT EXISTS idx_availability_date ON photographer_availability(date);
CREATE INDEX IF NOT EXISTS idx_availability_is_available ON photographer_availability(is_available);

-- ============================================================================
-- 3. EVENT & BOOKING MANAGEMENT TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS event_categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    icon VARCHAR(100),
    color_code VARCHAR(20),
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_categories_slug ON event_categories(slug);
CREATE INDEX IF NOT EXISTS idx_event_categories_display_order ON event_categories(display_order);

CREATE TABLE IF NOT EXISTS events (
    event_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id INT NOT NULL,
    category_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    event_date DATE NOT NULL,
    event_time TIME,
    end_date DATE,
    location VARCHAR(255),
    venue_name VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    expected_attendees INT,
    budget_range VARCHAR(100),
    min_budget DECIMAL(10, 2),
    max_budget DECIMAL(10, 2),
    requirements TEXT,
    status event_status_enum DEFAULT 'open',
    visibility event_visibility_enum DEFAULT 'public',
    images JSONB,
    tags JSONB,
    views_count INT DEFAULT 0,
    interested_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_events_creator FOREIGN KEY (creator_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES event_categories(category_id)
);

CREATE INDEX IF NOT EXISTS idx_events_creator_id ON events(creator_id);
CREATE INDEX IF NOT EXISTS idx_events_category_id ON events(category_id);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events(event_date);
CREATE INDEX IF NOT EXISTS idx_events_status ON events(status);
CREATE INDEX IF NOT EXISTS idx_events_city ON events(city);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    photographer_id INT NOT NULL,
    event_id INT,
    booking_date DATE NOT NULL,
    booking_time TIME,
    end_date DATE,
    duration_hours DECIMAL(5, 2),
    location VARCHAR(255),
    venue_name VARCHAR(255),
    event_type VARCHAR(100),
    total_amount DECIMAL(10, 2) NOT NULL,
    advance_amount DECIMAL(10, 2),
    pending_amount DECIMAL(10, 2),
    currency VARCHAR(10) DEFAULT 'INR',
    status booking_status_enum DEFAULT 'pending',
    payment_status booking_payment_status_enum DEFAULT 'unpaid',
    special_requirements TEXT,
    cancellation_reason TEXT,
    cancelled_by INT,
    cancelled_at TIMESTAMP,
    confirmed_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookings_customer FOREIGN KEY (customer_id) REFERENCES users(user_id),
    CONSTRAINT fk_bookings_photographer FOREIGN KEY (photographer_id) REFERENCES photographers(photographer_id),
    CONSTRAINT fk_bookings_event FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_bookings_customer_id ON bookings(customer_id);
CREATE INDEX IF NOT EXISTS idx_bookings_photographer_id ON bookings(photographer_id);
CREATE INDEX IF NOT EXISTS idx_bookings_booking_date ON bookings(booking_date);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_payment_status ON bookings(payment_status);

CREATE TABLE IF NOT EXISTS booking_payments (
    payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'INR',
    payment_type payment_type_enum NOT NULL,
    payment_method VARCHAR(50),
    payment_status payment_status_enum DEFAULT 'pending',
    transaction_id VARCHAR(255) UNIQUE,
    payment_gateway VARCHAR(50),
    gateway_response JSONB,
    payment_date TIMESTAMP,
    refund_amount DECIMAL(10, 2),
    refund_date TIMESTAMP,
    refund_reason TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_booking_payments_booking_id ON booking_payments(booking_id);
CREATE INDEX IF NOT EXISTS idx_booking_payments_transaction_id ON booking_payments(transaction_id);
CREATE INDEX IF NOT EXISTS idx_booking_payments_status ON booking_payments(payment_status);
CREATE INDEX IF NOT EXISTS idx_booking_payments_payment_date ON booking_payments(payment_date);

CREATE TABLE IF NOT EXISTS booking_reviews (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT NOT NULL UNIQUE,
    photographer_id INT NOT NULL,
    customer_id INT NOT NULL,
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_text TEXT,
    review_images JSONB,
    response_text TEXT,
    response_date TIMESTAMP,
    is_verified BOOLEAN DEFAULT FALSE,
    is_featured BOOLEAN DEFAULT FALSE,
    helpful_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_photographer FOREIGN KEY (photographer_id) REFERENCES photographers(photographer_id),
    CONSTRAINT fk_reviews_customer FOREIGN KEY (customer_id) REFERENCES users(user_id)
);

CREATE INDEX IF NOT EXISTS idx_booking_reviews_photographer_id ON booking_reviews(photographer_id);
CREATE INDEX IF NOT EXISTS idx_booking_reviews_rating ON booking_reviews(rating);
CREATE INDEX IF NOT EXISTS idx_booking_reviews_is_featured ON booking_reviews(is_featured);

-- ============================================================================
-- 4. SOCIAL FEATURES TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS posts (
    post_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    content_type post_content_type_enum NOT NULL DEFAULT 'image',
    caption TEXT,
    media_urls JSONB,
    thumbnail_url VARCHAR(500),
    location VARCHAR(255),
    tags JSONB,
    mentions JSONB,
    likes_count INT DEFAULT 0,
    comments_count INT DEFAULT 0,
    shares_count INT DEFAULT 0,
    views_count INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    is_featured BOOLEAN DEFAULT FALSE,
    visibility post_visibility_enum DEFAULT 'public',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_posts_user_id ON posts(user_id);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at);
CREATE INDEX IF NOT EXISTS idx_posts_is_featured ON posts(is_featured);
CREATE INDEX IF NOT EXISTS idx_posts_caption_fulltext ON posts USING GIN (to_tsvector('english', caption));

CREATE TABLE IF NOT EXISTS post_likes (
    like_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INT NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
    CONSTRAINT fk_post_likes_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_post_like UNIQUE (post_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_post_likes_post_id ON post_likes(post_id);
CREATE INDEX IF NOT EXISTS idx_post_likes_user_id ON post_likes(user_id);

CREATE TABLE IF NOT EXISTS post_comments (
    comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INT NOT NULL,
    user_id INT NOT NULL,
    parent_comment_id INT,
    comment_text TEXT NOT NULL,
    likes_count INT DEFAULT 0,
    is_edited BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_post_comments_post FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE,
    CONSTRAINT fk_post_comments_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_post_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES post_comments(comment_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_post_comments_post_id ON post_comments(post_id);
CREATE INDEX IF NOT EXISTS idx_post_comments_user_id ON post_comments(user_id);
CREATE INDEX IF NOT EXISTS idx_post_comments_parent_comment_id ON post_comments(parent_comment_id);

CREATE TABLE IF NOT EXISTS collections (
    collection_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    thumbnail_url VARCHAR(500),
    images JSONB,
    category VARCHAR(100),
    tags JSONB,
    is_public BOOLEAN DEFAULT TRUE,
    likes_count INT DEFAULT 0,
    saves_count INT DEFAULT 0,
    views_count INT DEFAULT 0,
    is_featured BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_collections_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_collections_user_id ON collections(user_id);
CREATE INDEX IF NOT EXISTS idx_collections_category ON collections(category);
CREATE INDEX IF NOT EXISTS idx_collections_is_public ON collections(is_public);
CREATE INDEX IF NOT EXISTS idx_collections_is_featured ON collections(is_featured);

-- ============================================================================
-- 5. COMMUNICATION TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS messages (
    message_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INT NOT NULL,
    receiver_id INT NOT NULL,
    message_text TEXT NOT NULL,
    message_type message_type_enum DEFAULT 'text',
    attachment_url VARCHAR(500),
    is_read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMP,
    is_deleted_by_sender BOOLEAN DEFAULT FALSE,
    is_deleted_by_receiver BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_receiver FOREIGN KEY (receiver_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_messages_sender_id ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_receiver_id ON messages(receiver_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(sender_id, receiver_id, created_at);
CREATE INDEX IF NOT EXISTS idx_messages_is_read ON messages(is_read);

CREATE TABLE IF NOT EXISTS notifications (
    notification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    type notification_type_enum NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    link VARCHAR(500),
    data JSONB,
    is_read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMP,
    priority notification_priority_enum DEFAULT 'medium',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_type ON notifications(type);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at);

-- ============================================================================
-- TIMESTAMP TRIGGERS
-- ============================================================================

DROP TRIGGER IF EXISTS users_set_timestamp ON users;
CREATE TRIGGER users_set_timestamp
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS user_profiles_set_timestamp ON user_profiles;
CREATE TRIGGER user_profiles_set_timestamp
BEFORE UPDATE ON user_profiles
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS user_roles_set_timestamp ON user_roles;
CREATE TRIGGER user_roles_set_timestamp
BEFORE UPDATE ON user_roles
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS user_sessions_set_timestamp ON user_sessions;
CREATE TRIGGER user_sessions_set_timestamp
BEFORE UPDATE ON user_sessions
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS photographers_set_timestamp ON photographers;
CREATE TRIGGER photographers_set_timestamp
BEFORE UPDATE ON photographers
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS photographer_portfolios_set_timestamp ON photographer_portfolios;
CREATE TRIGGER photographer_portfolios_set_timestamp
BEFORE UPDATE ON photographer_portfolios
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS photographer_availability_set_timestamp ON photographer_availability;
CREATE TRIGGER photographer_availability_set_timestamp
BEFORE UPDATE ON photographer_availability
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS event_categories_set_timestamp ON event_categories;
CREATE TRIGGER event_categories_set_timestamp
BEFORE UPDATE ON event_categories
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS events_set_timestamp ON events;
CREATE TRIGGER events_set_timestamp
BEFORE UPDATE ON events
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS bookings_set_timestamp ON bookings;
CREATE TRIGGER bookings_set_timestamp
BEFORE UPDATE ON bookings
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS booking_payments_set_timestamp ON booking_payments;
CREATE TRIGGER booking_payments_set_timestamp
BEFORE UPDATE ON booking_payments
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS booking_reviews_set_timestamp ON booking_reviews;
CREATE TRIGGER booking_reviews_set_timestamp
BEFORE UPDATE ON booking_reviews
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS posts_set_timestamp ON posts;
CREATE TRIGGER posts_set_timestamp
BEFORE UPDATE ON posts
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS post_comments_set_timestamp ON post_comments;
CREATE TRIGGER post_comments_set_timestamp
BEFORE UPDATE ON post_comments
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS collections_set_timestamp ON collections;
CREATE TRIGGER collections_set_timestamp
BEFORE UPDATE ON collections
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS messages_set_timestamp ON messages;
CREATE TRIGGER messages_set_timestamp
BEFORE UPDATE ON messages
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS notifications_set_timestamp ON notifications;
CREATE TRIGGER notifications_set_timestamp
BEFORE UPDATE ON notifications
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- BUSINESS LOGIC TRIGGERS
-- ============================================================================

CREATE OR REPLACE FUNCTION update_photographer_rating_after_review()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE photographers
    SET rating = COALESCE((
            SELECT AVG(rating)::DECIMAL(3,2)
            FROM booking_reviews
            WHERE photographer_id = NEW.photographer_id
        ), 0),
        total_reviews = (
            SELECT COUNT(*)
            FROM booking_reviews
            WHERE photographer_id = NEW.photographer_id
        )
    WHERE photographer_id = NEW.photographer_id;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_photographer_rating_after_review ON booking_reviews;
CREATE TRIGGER trg_update_photographer_rating_after_review
AFTER INSERT ON booking_reviews
FOR EACH ROW
EXECUTE FUNCTION update_photographer_rating_after_review();

CREATE OR REPLACE FUNCTION increment_post_likes()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts
    SET likes_count = likes_count + 1
    WHERE post_id = NEW.post_id;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION decrement_post_likes()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts
    SET likes_count = GREATEST(likes_count - 1, 0)
    WHERE post_id = OLD.post_id;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_increment_post_likes ON post_likes;
CREATE TRIGGER trg_increment_post_likes
AFTER INSERT ON post_likes
FOR EACH ROW
EXECUTE FUNCTION increment_post_likes();

DROP TRIGGER IF EXISTS trg_decrement_post_likes ON post_likes;
CREATE TRIGGER trg_decrement_post_likes
AFTER DELETE ON post_likes
FOR EACH ROW
EXECUTE FUNCTION decrement_post_likes();

CREATE OR REPLACE FUNCTION increment_post_comments()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts
    SET comments_count = comments_count + 1
    WHERE post_id = NEW.post_id;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION decrement_post_comments()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE posts
    SET comments_count = GREATEST(comments_count - 1, 0)
    WHERE post_id = OLD.post_id;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_increment_post_comments ON post_comments;
CREATE TRIGGER trg_increment_post_comments
AFTER INSERT ON post_comments
FOR EACH ROW
EXECUTE FUNCTION increment_post_comments();

DROP TRIGGER IF EXISTS trg_decrement_post_comments ON post_comments;
CREATE TRIGGER trg_decrement_post_comments
AFTER DELETE ON post_comments
FOR EACH ROW
EXECUTE FUNCTION decrement_post_comments();

-- ============================================================================
-- VIEWS
-- ============================================================================

CREATE OR REPLACE VIEW view_users_complete AS
SELECT 
    u.user_id,
    u.email,
    u.user_type,
    u.is_verified,
    u.is_active,
    u.last_login,
    u.created_at AS user_created_at,
    up.full_name,
    up.avatar_url,
    up.bio,
    up.phone,
    up.location,
    up.city,
    up.state,
    up.country
FROM users u
LEFT JOIN user_profiles up ON u.user_id = up.user_id;

CREATE OR REPLACE VIEW view_photographers_complete AS
SELECT 
    p.*,
    u.email,
    u.is_verified AS user_verified,
    u.is_active AS user_active,
    up.full_name,
    up.avatar_url,
    up.bio,
    up.phone,
    up.location,
    up.city,
    up.state
FROM photographers p
JOIN users u ON p.user_id = u.user_id
JOIN user_profiles up ON u.user_id = up.user_id;

CREATE OR REPLACE VIEW view_bookings_active AS
SELECT 
    b.*,
    up_customer.full_name AS customer_name,
    up_customer.phone AS customer_phone,
    p.business_name AS photographer_business,
    up_photographer.full_name AS photographer_name,
    up_photographer.phone AS photographer_phone,
    e.title AS event_title,
    ec.category_name AS event_category
FROM bookings b
JOIN user_profiles up_customer ON b.customer_id = up_customer.user_id
JOIN photographers p ON b.photographer_id = p.photographer_id
JOIN user_profiles up_photographer ON p.user_id = up_photographer.user_id
LEFT JOIN events e ON b.event_id = e.event_id
LEFT JOIN event_categories ec ON e.category_id = ec.category_id
WHERE b.status IN ('pending', 'confirmed', 'in_progress');

-- ============================================================================
-- END OF SCHEMA
-- ============================================================================


